
language: node_js
node_js:
  - "4.4.3"
before_script:
  - npm install -g angular-cli
  - npm install -g gulp
script: 
  - gulp build-and-run-coverage-in-seq
after_success:
  - 'cat ./coverage/lcov-frontend-backend-remapped.info | ./node_modules/.bin/coveralls'